dorado:
  port: 8081
sftpd:
  port: 2007
  rootDir: /tmp
  serverName: sftp-server
  registerServerUrl: http://localhost:8081/info/register-server
  registerServer: true
  classPath: ../lib/*
  mainClass: com.cib.edip.edipsftpserver.sftpd.SftpServer
  hostKey: ./keys/edip-sftpserver-host-rsa-key
